#!/bin/bash

# Source .bashrc if not already loaded (ensures PATH loads in login shells)
if [ -z "$_BASHRC_LOADED" ] && [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# This is the part that will get all the variables
if [ -f ~/.bash_variables ]; then
   . ~/.bash_variables
fi

## adding the .bash_aliases file
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# This will contain global things for bash
if [ -f ~/.bash_global ]; then
    . ~/.bash_global
fi

# This is the git completion shortcuts
if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi

# this will load the prompt that users will be getting when access the ssh
if [ -f ~/.bash_prompt ]; then
    . ~/.bash_prompt
fi

## adding the .bash_prompt file
if [ -f ~/.zshrc ]; then
    . ~/.zshrc
fi