#!/bin/bash

## adding the .bash_g file
if [ -f ~/.bash_g ]; then
    . ~/.bash_g
fi

## adding the .bash_aliases file
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

## installed by strubloid
if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi

## adding the .bash_prompt file
if [ -f ~/.bash_prompt ]; then
    . ~/.bash_prompt
fi
