# WSL localhost mapping to Windows host
export WSL_HOST=$(ip route show | grep default | awk '{print $3}')

# Function to automatically map localhost to Windows host for curl
curl() {
  local args=("$@")
  local mapped=false
  
  # Loop through all arguments to find and replace localhost URLs
  for i in "${!args[@]}"; do
    if [[ "${args[i]}" == *"localhost"* ]]; then
      args[i]="${args[i]/localhost/$WSL_HOST}"
      if [[ "$mapped" == false ]]; then
        echo "WSL2: Mapping localhost to Windows host: $WSL_HOST"
        mapped=true
      fi
    fi
  done
  
  command curl "${args[@]}"
}

# WSL DNS Fix Functions
function wsl-dns-fix() {
    echo "🔧 Fixing WSL DNS resolution..."
    
    # Create a proper resolv.conf with fallback DNS servers
    echo "# Generated by wsl-dns-fix" | sudo tee /etc/resolv.conf > /dev/null
    echo "nameserver 8.8.8.8" | sudo tee -a /etc/resolv.conf > /dev/null
    echo "nameserver 8.8.4.4" | sudo tee -a /etc/resolv.conf > /dev/null
    echo "nameserver 1.1.1.1" | sudo tee -a /etc/resolv.conf > /dev/null
    echo "search ." | sudo tee -a /etc/resolv.conf > /dev/null
    
    # Restart systemd-resolved if it's running
    if systemctl is-active --quiet systemd-resolved; then
        echo "🔄 Restarting systemd-resolved..."
        sudo systemctl restart systemd-resolved
    fi
    
    # Test DNS resolution
    echo "🧪 Testing DNS resolution..."
    if nslookup github.com > /dev/null 2>&1; then
        echo "✅ DNS resolution fixed! github.com is now reachable."
        echo "🔍 Testing SSH to GitHub..."
        ssh -T git@github.com -o ConnectTimeout=10 2>&1 | head -3
    else
        echo "❌ DNS resolution still not working. Please check your network connection."
    fi
}

function wsl-dns-status() {
    echo "📊 WSL DNS Status:"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "🔧 Current resolv.conf:"
    cat /etc/resolv.conf
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "🌐 systemd-resolved status:"
    resolvectl status 2>/dev/null || systemd-resolve --status 2>/dev/null || echo "systemd-resolved not available"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "🧪 Testing github.com resolution:"
    nslookup github.com 2>&1 | head -5
}

function wsl-dns-reset() {
    echo "🔄 Resetting WSL DNS to system default..."
    
    # Check if generateResolvConf is disabled in wsl.conf
    if grep -q "generateResolvConf.*false" /etc/wsl.conf 2>/dev/null; then
        echo "⚠️  Warning: generateResolvConf is disabled in /etc/wsl.conf"
        echo "    This prevents WSL from auto-generating DNS configuration."
        echo "    Use 'wsl-dns-fix' instead, or manually edit /etc/wsl.conf"
    else
        # Remove custom resolv.conf to let WSL regenerate it
        sudo rm -f /etc/resolv.conf
        sudo systemctl restart systemd-resolved 2>/dev/null || true
        echo "✅ DNS configuration reset. Please restart WSL to take effect:"
        echo "   wsl --shutdown && wsl"
    fi
}

# Quick aliases for DNS troubleshooting
alias dns-fix='wsl-dns-fix'
alias dns-status='wsl-dns-status'
alias dns-reset='wsl-dns-reset'